Repository HisTour/HisTour-Spring, pull requests merged in 2024-09, with the labels that each got.

#82 feat: 국경일 조회 API
  histour-application/src/main/java/trible/histour/application/domain/history/HistoryService.java
  histour-application/src/main/java/trible/histour/application/port/input/HistoryUseCase.java
  histour-application/src/main/java/trible/histour/application/port/input/dto/response/history/HolidayResponse.java
  histour-application/src/main/java/trible/histour/application/port/input/dto/response/history/HolidaysResponse.java
  histour-application/src/main/java/trible/histour/application/port/output/web/DataPort.java
  histour-application/src/main/java/trible/histour/application/port/output/web/dto/response/DataHolidayResponse.java
  histour-bootstrap/build.gradle
  histour-bootstrap/src/main/resources/application-local.yml
  histour-bootstrap/src/main/resources/application-prod.yml
  histour-input-http/src/main/java/trible/histour/input/http/controller/HistoryApi.java
  histour-input-http/src/main/java/trible/histour/input/http/controller/docs/HistoryApiDocs.java
  histour-output-web/build.gradle
  histour-output-web/data/src/main/java/trible/histour/output/web/data/adapter/DataAdapter.java
  histour-output-web/data/src/main/java/trible/histour/output/web/data/config/DataConfig.java
  histour-output-web/data/src/main/java/trible/histour/output/web/data/config/DataProperties.java
  histour-output-web/data/src/main/resources/data-config/application-local.yml
  histour-output-web/data/src/main/resources/data-config/application-prod.yml
  settings.gradle
Labels: feat

#83 fix: 추천 관광지 조회 API
  histour-application/src/main/java/trible/histour/application/domain/attraction/Attraction.java
  histour-application/src/main/java/trible/histour/application/domain/attraction/AttractionService.java
  histour-application/src/main/java/trible/histour/application/port/input/dto/response/attraction/AttractionResponse.java
  histour-application/src/main/java/trible/histour/application/port/input/dto/response/attraction/AttractionsResponse.java
  histour-application/src/main/java/trible/histour/application/port/output/persistence/AttractionPort.java
  histour-application/src/main/java/trible/histour/application/port/output/web/DataPort.java
  histour-application/src/main/java/trible/histour/application/port/output/web/dto/response/DataAttractionResponse.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/adapter/AttractionAdapter.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/AttractionEntity.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/repository/AttractionRepository.java
  histour-output-web/data/src/main/java/trible/histour/output/web/data/adapter/DataAdapter.java
  histour-output-web/data/src/main/java/trible/histour/output/web/data/config/DataProperties.java
  histour-output-web/data/src/main/resources/data-config/application-local.yml
  histour-output-web/data/src/main/resources/data-config/application-prod.yml
Labels: fix

#85 add: 추가 필요 값 추가
  histour-application/src/main/java/trible/histour/application/domain/mission/Mission.java
  histour-application/src/main/java/trible/histour/application/domain/quiz/QuizType.java
  histour-application/src/main/java/trible/histour/application/port/input/dto/response/mission/MissionResponse.java
  histour-input-http/src/main/java/trible/histour/input/http/controller/docs/AttractionApiDocs.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/MissionEntity.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/PlaceEntity.java
Labels: add

#86 feature: 미션 해금 api
  histour-application/src/main/java/trible/histour/application/domain/mission/MemberMission.java
  histour-application/src/main/java/trible/histour/application/domain/mission/MissionService.java
  histour-application/src/main/java/trible/histour/application/port/input/MissionUseCase.java
  histour-application/src/main/java/trible/histour/application/port/output/persistence/MemberMissionPort.java
  histour-input-http/src/main/java/trible/histour/input/http/controller/MissionApi.java
  histour-input-http/src/main/java/trible/histour/input/http/controller/docs/MissionApiDocs.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/adapter/MemberMissionAdapter.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/MemberMissionEntity.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/repository/MemberMissionRepository.java
Labels: feat

#87 add: 장소별 서브미션 고르는 이미지 url 필드 추가
  histour-application/src/main/java/trible/histour/application/domain/place/Place.java
  histour-application/src/main/java/trible/histour/application/port/input/dto/response/place/PlaceResponse.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/PlaceEntity.java
Labels: add

#88 fix: 스웨거 설명 수정
  histour-application/src/main/java/trible/histour/application/port/input/dto/response/character/CharacterResponse.java
Labels: fix

#90 add: 캐릭터 얼굴 이미지 칼럼 추가
  histour-application/src/main/java/trible/histour/application/domain/character/CharacterImageInfo.java
  histour-application/src/main/java/trible/histour/application/port/input/dto/response/character/CharacterImageResponse.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/CharacterEntity.java
Labels: add

#92 add: 회원 정보 조회 API 예외 추가
  histour-application/src/main/java/trible/histour/application/domain/member/MemberService.java
  histour-common/src/main/java/trible/histour/common/exception/ExceptionCode.java
  histour-common/src/main/java/trible/histour/common/exception/HistourException.java
  histour-input-http/src/main/java/trible/histour/input/http/controller/dto/response/ExceptionResponse.java
  histour-input-http/src/main/java/trible/histour/input/http/web/ExceptionAdvice.java
  histour-input-http/src/main/java/trible/histour/input/http/web/HistourAuthenticationEntryPoint.java
Labels: add

#95 feat: recommend place API
  histour-application/src/main/java/trible/histour/application/domain/place/PlaceService.java
  histour-application/src/main/java/trible/histour/application/port/input/PlaceUseCase.java
  histour-application/src/main/java/trible/histour/application/port/input/dto/request/place/PlaceRecommendRequest.java
  histour-common/src/main/java/trible/histour/common/logger/HookLogger.java
  histour-common/src/main/java/trible/histour/common/logger/discord/DiscordWebhookLogger.java
  histour-common/src/main/java/trible/histour/common/logger/dto/request/DiscordRequest.java
  histour-common/src/main/resources/discord-config/application-local.yml
  histour-common/src/main/resources/discord-config/application-prod.yml
  histour-common/src/test/java/trible/histour/common/logger/discord/DiscordWebhookLoggerTest.java
  histour-input-http/src/main/java/trible/histour/input/http/controller/PlaceApi.java
  histour-input-http/src/main/java/trible/histour/input/http/controller/docs/PlaceApiDocs.java
  histour-input-http/src/main/java/trible/histour/input/http/web/ExceptionAdvice.java
Labels: feat

#93 feature: 퀴즈 채점 API
  histour-application/src/main/java/trible/histour/application/domain/attraction/AttractionService.java
  histour-application/src/main/java/trible/histour/application/domain/quiz/MemberQuiz.java
  histour-application/src/main/java/trible/histour/application/domain/quiz/QuizService.java
  histour-application/src/main/java/trible/histour/application/port/input/QuizUseCase.java
  histour-application/src/main/java/trible/histour/application/port/input/dto/request/quiz/QuizGradeRequest.java
  histour-application/src/main/java/trible/histour/application/port/input/dto/response/quiz/QuizGradeResponse.java
  histour-application/src/main/java/trible/histour/application/port/output/persistence/MemberMissionPort.java
  histour-application/src/main/java/trible/histour/application/port/output/persistence/MemberQuizPort.java
  histour-application/src/main/java/trible/histour/application/port/output/persistence/QuizPort.java
  histour-input-http/src/main/java/trible/histour/input/http/controller/QuizApi.java
  histour-input-http/src/main/java/trible/histour/input/http/controller/docs/MemberApiDocs.java
  histour-input-http/src/main/java/trible/histour/input/http/controller/docs/QuizApiDocs.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/adapter/MemberMissionAdapter.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/adapter/MemberQuizAdapter.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/adapter/QuizAdapter.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/repository/MemberMissionRepository.java
Labels: feat

#97 fix: 미션 해금 API + 퀴즈 목록 조회 API 재분배
  histour-application/src/main/java/trible/histour/application/domain/mission/MissionService.java
  histour-application/src/main/java/trible/histour/application/domain/quiz/QuizService.java
  histour-application/src/main/java/trible/histour/application/port/input/MissionUseCase.java
  histour-application/src/main/java/trible/histour/application/port/input/dto/request/mission/UpdatedMissionsRequest.java
  histour-application/src/main/java/trible/histour/application/port/output/persistence/MemberMissionPort.java
  histour-common/src/main/java/trible/histour/common/exception/ExceptionCode.java
  histour-input-http/src/main/java/trible/histour/input/http/controller/MissionApi.java
  histour-input-http/src/main/java/trible/histour/input/http/controller/docs/MissionApiDocs.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/adapter/MemberMissionAdapter.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/MemberMissionEntity.java
Labels: fix

#100 add: 미션 선택 이미지 필드 추가
  histour-application/src/main/java/trible/histour/application/port/input/dto/response/mission/MissionsResponse.java
Labels: add

#101 fix: 소셜로그인 API 수정
  histour-application/src/main/java/trible/histour/application/domain/auth/SocialInfo.java
  histour-application/src/main/java/trible/histour/application/domain/member/Member.java
  histour-application/src/main/java/trible/histour/application/domain/member/MemberService.java
  histour-application/src/main/java/trible/histour/application/port/input/MemberUseCase.java
  histour-application/src/main/java/trible/histour/application/port/input/dto/request/member/CharacterUpdateRequest.java
  histour-application/src/main/java/trible/histour/application/port/input/dto/request/member/MemberProfileUpdateRequest.java
  histour-application/src/main/java/trible/histour/application/port/input/dto/response/auth/SignInResponse.java
  histour-input-http/src/main/java/trible/histour/input/http/controller/MemberApi.java
  histour-input-http/src/main/java/trible/histour/input/http/controller/docs/MemberApiDocs.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/adapter/MemberAdapter.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/MemberEntity.java
  histour-output-web/oauth/src/main/java/trible/histour/output/web/oauth/adapter/AppleService.java
  histour-output-web/oauth/src/main/java/trible/histour/output/web/oauth/adapter/KakaoService.java
  histour-output-web/oauth/src/main/java/trible/histour/output/web/oauth/adapter/OauthAdapter.java
Labels: fix

#104 feat: 예외 핸들러 추가
  histour-input-http/src/main/java/trible/histour/input/http/web/ExceptionAdvice.java
Labels: add

#107 fix: 토큰 만료 시간 위치 이동
  histour-application/src/main/java/trible/histour/application/domain/auth/AuthService.java
  histour-application/src/main/resources/application-config/application-local.yml
  histour-application/src/main/resources/application-config/application-prod.yml
Labels: fix

#105 fix: 퀴즈 채점 API 수정
  histour-application/src/main/java/trible/histour/application/domain/quiz/QuizService.java
  histour-application/src/main/java/trible/histour/application/port/output/persistence/MemberQuizPort.java
  histour-common/src/main/java/trible/histour/common/exception/ExceptionCode.java
  histour-input-http/src/main/java/trible/histour/input/http/controller/docs/QuizApiDocs.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/adapter/MemberQuizAdapter.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/repository/MemberQuizRepository.java
Labels: fix

#109 delete: 미사용 코드 삭제
  histour-application/src/main/java/trible/histour/application/domain/member/Member.java
  histour-application/src/main/java/trible/histour/application/port/input/dto/response/member/MemberInfoResponse.java
  histour-output-web/oauth/src/main/java/trible/histour/output/web/oauth/adapter/AppleService.java
Labels: delete

#112 fix: grade api remove +1
  histour-application/src/main/java/trible/histour/application/domain/quiz/QuizService.java
Labels: fix

#110 feat: 챗봇 생성 API
  histour-application/src/main/java/trible/histour/application/domain/assistant/AssistantService.java
  histour-application/src/main/java/trible/histour/application/port/input/AssistantUseCase.java
  histour-application/src/main/java/trible/histour/application/port/input/dto/request/assistant/ChatAssistantRequest.java
  histour-application/src/main/java/trible/histour/application/port/input/dto/response/assistant/ChatAssistantResponse.java
  histour-application/src/main/java/trible/histour/application/port/output/web/DataPort.java
  histour-application/src/main/java/trible/histour/application/port/output/web/dto/request/ChatAssistantAiRequest.java
  histour-application/src/main/java/trible/histour/application/port/output/web/dto/response/ChatAssistantAiResponse.java
  histour-input-http/src/main/java/trible/histour/input/http/controller/AssistantApi.java
  histour-input-http/src/main/java/trible/histour/input/http/controller/docs/AssistantApiDocs.java
  histour-output-web/data/src/main/java/trible/histour/output/web/data/adapter/DataAdapter.java
  histour-output-web/data/src/main/java/trible/histour/output/web/data/config/DataProperties.java
  histour-output-web/data/src/main/resources/data-config/application-local.yml
  histour-output-web/data/src/main/resources/data-config/application-prod.yml
Labels: feat
