Repository HisTour/HisTour-Spring, pull requests merged in 2024-07, with the labels that each got.

#6 init: ERD modeling
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/aws.xml
  .idea/checkstyle-idea.xml
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  build.gradle
  histour-application/src/main/java/trible/histour/application/domain/character/Character.java
  histour-application/src/main/java/trible/histour/application/domain/character/CharacterType.java
  histour-application/src/main/java/trible/histour/application/domain/member/Member.java
  histour-application/src/main/java/trible/histour/application/domain/member/SocialType.java
  histour-application/src/main/java/trible/histour/application/domain/membermission/MemberMission.java
  histour-application/src/main/java/trible/histour/application/domain/membermission/MissionState.java
  histour-application/src/main/java/trible/histour/application/domain/mission/Mission.java
  histour-application/src/main/java/trible/histour/application/domain/mission/MissionType.java
  histour-application/src/main/java/trible/histour/application/domain/place/Place.java
  histour-application/src/main/java/trible/histour/application/domain/place/RegionType.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/config/JpaAuditingConfig.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/config/JpaConfig.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/BaseEntity.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/CharacterEntity.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/MemberEntity.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/MemberMissionEntity.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/MissionEntity.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/PlaceEntity.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/repository/CharacterRepository.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/repository/MemberMissionRepository.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/repository/MissionRepository.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/repository/PlaceRepository.java
Labels: init

#15 add: mission type list column
  histour-application/src/main/java/trible/histour/application/domain/mission/Mission.java
  histour-application/src/main/java/trible/histour/application/domain/mission/MissionType.java
  histour-bootstrap/src/test/java/trible/histour/bootstrap/HistourBootstrapApplicationTests.java
  histour-output-postgresql/build.gradle
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/converter/MissionTypeListConverter.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/MissionEntity.java
Labels: add

#16 init: 필요한 설정파일(application.yml) 설정
  .gitignore
  docker/docker-compose.yml
  histour-application/src/main/java/trible/histour/application/domain/character/CharacterType.java
  histour-application/src/main/java/trible/histour/application/domain/membermission/MissionState.java
  histour-application/src/main/java/trible/histour/application/domain/mission/MissionType.java
  histour-application/src/main/java/trible/histour/application/domain/place/RegionType.java
  histour-bootstrap/src/main/resources/application-local.yml
  histour-bootstrap/src/main/resources/application-prod.yml
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/config/JpaAuditingConfig.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/config/JpaConfig.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/config/PostgresqlConfig.java
  histour-output-postgresql/src/main/resources/application-local.yml
  histour-output-postgresql/src/main/resources/application-prod.yml
  histour-output-postgresql/src/main/resources/database-config/application-local.yml
  histour-output-postgresql/src/main/resources/database-config/application-prod.yml
Labels: init

#18 add: Secret Manager 도입
  histour-bootstrap/src/main/java/trible/histour/bootstrap/secret/SecretProcessor.java
  histour-bootstrap/src/main/resources/META-INF/spring.factories
  histour-bootstrap/src/main/resources/application-local.yml
  histour-bootstrap/src/main/resources/application-prod.yml
  histour-output-postgresql/src/main/resources/database-config/application-local.yml
  histour-output-postgresql/src/main/resources/database-config/application-prod.yml
Labels: add

#20 feat: Security 기능 구현
  build.gradle
  histour-application/build.gradle
  histour-application/src/main/java/trible/histour/application/domain/auth/AuthService.java
  histour-application/src/main/java/trible/histour/application/domain/auth/HistourAuthentication.java
  histour-application/src/main/java/trible/histour/application/domain/auth/SecretKeyFactory.java
  histour-application/src/main/java/trible/histour/application/domain/auth/TokenManager.java
  histour-application/src/main/java/trible/histour/application/domain/member/Member.java
  histour-application/src/main/resources/application-config/application-local.yml
  histour-application/src/main/resources/application-config/application-prod.yml
  histour-application/src/test/java/trible/histour/application/TokenManagerTest.java
  histour-bootstrap/src/main/resources/application-local.yml
  histour-bootstrap/src/main/resources/application-prod.yml
  histour-common/src/main/java/trible/histour/common/exception/ExceptionCode.java
  histour-input-http/build.gradle
  histour-input-http/src/main/java/trible/histour/input/http/config/SecurityConfig.java
  histour-input-http/src/main/java/trible/histour/input/http/controller/TestApi.java
  histour-input-http/src/main/java/trible/histour/input/http/controller/docs/TestApiDocs.java
  histour-input-http/src/main/java/trible/histour/input/http/controller/dto/response/ExceptionResponse.java
  histour-input-http/src/main/java/trible/histour/input/http/docs/TestApiDocs.java
  histour-input-http/src/main/java/trible/histour/input/http/web/HistourAuthenticationEntryPoint.java
  histour-input-http/src/main/java/trible/histour/input/http/web/HistourAuthenticationFilter.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/MemberEntity.java
Labels: feat

#21 init: Issue, PR Template 추가
  .github/ISSUE_TEMPLATE/1-feature-report.yml
  .github/ISSUE_TEMPLATE/2-bug-report.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, init

#23 add: custom exception
  histour-bootstrap/build.gradle
  histour-bootstrap/src/main/java/trible/histour/bootstrap/secret/SecretProcessor.java
  histour-common/src/main/java/trible/histour/common/exception/ExceptionCode.java
  histour-common/src/main/java/trible/histour/common/exception/HisTourException.java
  histour-common/src/main/java/trible/histour/common/exception/HistourException.java
  histour-input-http/src/main/java/trible/histour/input/http/controller/dto/response/ExceptionResponse.java
  histour-input-http/src/main/java/trible/histour/input/http/web/ExceptionAdvice.java
  histour-input-http/src/main/java/trible/histour/input/http/web/HistourAuthenticationEntryPoint.java
  histour-output-postgresql/build.gradle
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/converter/MissionTypeListConverter.java
Labels: add

#24 Chore: check style
  .DS_Store
  build.gradle
  checkstyle/naver-checkstyle-rules.xml
  checkstyle/naver-checkstyle-suppresions.xml
  histour-application/src/main/java/trible/histour/application/domain/auth/AuthService.java
  histour-application/src/main/java/trible/histour/application/domain/auth/HistourAuthentication.java
  histour-application/src/main/java/trible/histour/application/domain/auth/SecretKeyFactory.java
  histour-application/src/main/java/trible/histour/application/domain/auth/TokenManager.java
  histour-application/src/main/java/trible/histour/application/domain/character/Character.java
  histour-application/src/main/java/trible/histour/application/domain/member/Member.java
  histour-application/src/main/java/trible/histour/application/domain/membermission/MemberMission.java
  histour-application/src/main/java/trible/histour/application/domain/mission/Mission.java
  histour-application/src/main/java/trible/histour/application/domain/place/Place.java
  histour-application/src/main/java/trible/histour/application/port/output/persistence/MemberPort.java
  histour-application/src/main/java/trible/histour/application/port/output/persistence/TestPort.java
  histour-bootstrap/src/main/java/trible/histour/bootstrap/secret/SecretProcessor.java
  histour-common/src/main/java/trible/histour/common/exception/ExceptionCode.java
  histour-common/src/main/java/trible/histour/common/exception/HistourException.java
  histour-input-http/src/main/java/trible/histour/input/http/config/SecurityConfig.java
  histour-input-http/src/main/java/trible/histour/input/http/controller/dto/response/ExceptionResponse.java
  histour-input-http/src/main/java/trible/histour/input/http/web/ExceptionAdvice.java
  histour-input-http/src/main/java/trible/histour/input/http/web/HistourAuthenticationEntryPoint.java
  histour-input-http/src/main/java/trible/histour/input/http/web/HistourAuthenticationFilter.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/converter/MissionTypeListConverter.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/BaseEntity.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/CharacterEntity.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/MemberEntity.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/MemberMissionEntity.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/MissionEntity.java
  histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/PlaceEntity.java
  settings.gradle
Labels: chore

#27 init: Webhook Logger 추가
  histour-application/src/test/java/trible/histour/application/TokenManagerTest.java
  histour-bootstrap/src/main/resources/application-local.yml
  histour-bootstrap/src/main/resources/application-prod.yml
  histour-common/build.gradle
  histour-common/src/main/java/trible/histour/common/logger/HookLogger.java
  histour-common/src/main/java/trible/histour/common/logger/discord/DiscordWebhookLogger.java
  histour-common/src/main/java/trible/histour/common/logger/dto/request/DiscordRequest.java
  histour-common/src/main/java/trible/histour/common/logger/dto/request/LoggerRequest.java
  histour-common/src/main/resources/discord-config/application-local.yml
  histour-common/src/main/resources/discord-config/application-prod.yml
  histour-common/src/test/java/trible/histour/common/logger/discord/DiscordWebhookLoggerTest.java
  histour-common/src/test/java/trible/histour/common/logger/discord/TestConfiguration.java
  histour-common/src/test/resources/application-test.yml
  histour-input-http/src/main/java/trible/histour/input/http/config/SecurityConfig.java
  histour-input-http/src/main/java/trible/histour/input/http/web/ExceptionAdvice.java
Labels: init
